export * from './use-application'
export * from './use-click-outside'
export * from './use-cookie'
export * from './use-debounce'
export * from './use-dispatch'
export * from './use-hover'
export * from './use-idle'
export * from './use-intersection'
export * from './use-lazy-load'
export * from './use-match-media'
export * from './use-memo'
export * from './use-meta'
export * from './use-mutation'
export * from './use-resize'
export * from './use-target-mutation'
export * from './use-throttle'
export * from './use-transition'
export * from './use-visibility'
export * from './use-window-focus'
export * from './use-window-resize'

export function useHotkeys() {
  throw '[stimulus-use] Notice: The import for `useHotkeys()` has been moved from `stimulus-use` to `stimulus-use/hotkeys`. \nPlease change the import accordingly and add `hotkey-js` as a dependency to your project. \n\nFor more information see: https://stimulus-use.github.io/stimulus-use/#/use-hotkeys?id=importing-the-behavior'
}
