name: dev-builds

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'builds/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install
      - run: yarn build

      - name: Publish dev build
        run: .github/scripts/publish-dev-build 'stimulus-use:${{ secrets.STIMULUSUSE_DEV_BUILDS_TOKEN }}'
